name: Run B0

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  my_job:
    runs-on: ubuntu-latest
    timeout-minutes: 358

    steps:
    - name: Checkout Public Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip xvfb libxi6 || true
        wget -O /tmp/chromedriver.zip https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.88/linux64/chromedriver-linux64.zip
        unzip /tmp/chromedriver.zip -d /usr/local/bin/

    - name: Install Google Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable



    - name: Run script
      run: |
        sudo Xvfb :99 -ac &
        python script.py
